### ISSUE TITLE
[Request] Samples for subscale WaveRNN

### ISSUE THREAD

**Issue by francislata** [papercup-open-source/subscale-wavernn#1]
Hi there @lfogliantis ! Thank you for this awesome repo and blogpost. I’m curious to hear the quality with subscaling turned on. Is it possible to hear some samples from when you trained the model?

Thank you!

**Comment by lfogliantis** [comment]
Hey @francislata thanks for comment and interest - unfortunately we have only trained on proprietary data so I'm unable to share any of those samples.

Though it should be relatively straightforward to run it on the version of Sharvard linked in the readme in case you've got some spare compute!

**Comment by francislata** [comment]
@lfogliantis I believe I remember trying to train it but stopped it because of poor results - it was early on the training process too so there's that.

It would be awesome to provide some public dataset examples generated from this model modification to prove that it maintains quality while being able to generate samples at a faster rate.

**Comment by lfogliantis** [comment]
@francislata if you're still curious to hear how it sounds I've just added a link to some samples in the readme - this was trained on Sharvard for 1M iters with the current hparams
